### ISSUE TITLE
自动批量完成理符任务问题

### ISSUE THREAD

**Issue by DeepseaXX** [AtmoOmen/DalamudPlugins#1]
开启了YesAlready的自动完成任务后，日志提示报错之后停止不动。
```
2024-01-18 18:25:06.972 +09:00 [WRN] [ECommons] [Daily Routines] Clearing 0 remaining tasks because of timeout
2024-01-18 18:25:06.972 +09:00 [WRN] [ECommons] [Daily Routines] Task ClickHqSubmit took too long to execute
   at ECommons.Automation.TaskManager.Tick(Object _) in D:\young\Documents\GitHub\DailyRoutines\ECommons\ECommons\Automation\TaskManager.cs:line 284
```

关闭了YesAlready之后，卡在任务完成界面，提示类似的报错，如果立刻手动点击任务完成则提示`Clearing 9 remaining tasks`并卡住不动，如果稍等一会再手动点击任务完成则可顺利进入下一轮（我也不知道为什么会这样好神奇）。

```
2024-01-18 18:30:48.487 +09:00 [WRN] [ECommons] [Daily Routines] Clearing 1 remaining tasks because of timeout
2024-01-18 18:30:48.487 +09:00 [WRN] [ECommons] [Daily Routines] Task ClickSelectQuest took too long to execute
   at ECommons.Automation.TaskManager.Tick(Object _) in D:\young\Documents\GitHub\DailyRoutines\ECommons\ECommons\Automation\TaskManager.cs:line 284
```

**Comment by DeepseaXX** [comment]
回错repo，close一下
